import type { ProProduct } from "./types";

/*
 * SAMPLE CATALOG. Dimensions, prices and lead times are realistic placeholders
 * for layout and flow testing. Replace with manufacturer-confirmed data before
 * launch; see the sample notice in lib/site.ts.
 */

const specSheet = (slug: string) => ({ kind: "spec" as const, label: "Spec sheet", format: "PDF / print", href: `/pro/products/${slug}/spec-sheet` });
const install = { kind: "install" as const, label: "Install guide", format: "PDF", href: null };
const cad = { kind: "cad" as const, label: "CAD drawing", format: "DWG · DXF", href: null };

export const proProducts: ProProduct[] = [
  {
    storefront: "pro",
    slug: "park-station-400",
    name: "Park Station 400",
    category: "waste-stations",
    model: "FF-WS400",
    summary: "Holds 400 header-pack bags and a 10-gallon bin on a single 2-3/8\" post.",
    description: [
      "The station most parks start with. The dispenser takes any standard header-pack bag, the bin has a hinged lid and a liner ring, and the sign panel ships with our standard pickup text or yours.",
      "Everything bolts to a single 2-3/8\" OD post set 18\" in concrete. Two people can install it in under an hour.",
    ],
    highlights: ["Holds 400 bags", "10 gal bin with lid", "Powder-coated steel", "Mounts to a 2-3/8\" post"],
    specs: [
      { label: "Overall size", value: "16 × 13 × 72 in", note: "W × D × H above grade" },
      { label: "Shipping weight", value: "38 lb" },
      { label: "Materials", value: "14 ga steel body, 16 ga lid" },
      { label: "Finish", value: "Polyester powder coat, Park Green" },
      { label: "Capacity", value: "400 bags · 10 gal bin" },
      { label: "Mounting", value: "2-3/8\" OD post, 18\" embed", note: "post included" },
      { label: "Bag type", value: "Header pack, any brand" },
      { label: "Warranty", value: "5 yr finish · 10 yr structure" },
      { label: "Country of origin", value: "USA", note: "per manufacturer" },
      { label: "Lead time", value: "2–3 weeks" },
    ],
    leadTime: "Ships in 2–3 weeks",
    pricing: {
      kind: "tiers",
      unit: "each",
      tiers: [
        { minQty: 1, maxQty: 4, priceCents: 38900 },
        { minQty: 5, maxQty: 19, priceCents: 35900 },
        { minQty: 20, maxQty: null, priceCents: 32900 },
      ],
    },
    drawing: {
      title: "Park Station 400",
      number: "WS400-01",
      views: [
        {
          name: "Front",
          width: 16,
          height: 72,
          prims: [
            { t: "rect", x: 6.8, y: 0, w: 2.4, h: 56 },
            { t: "rect", x: 0, y: 56, w: 16, h: 16, r: 0.3 },
            { t: "rect", x: 1.2, y: 57.2, w: 13.6, h: 13.6, hidden: true },
            { t: "rect", x: 3, y: 40, w: 10, h: 13, r: 0.4 },
            { t: "line", x1: 5, y1: 42, x2: 11, y2: 42 },
            { t: "rect", x: 1, y: 14, w: 14, h: 20, r: 0.6 },
            { t: "rect", x: 0.6, y: 32, w: 14.8, h: 3, r: 0.4 },
            { t: "line", x1: 8, y1: 0, x2: 8, y2: 72, center: true },
          ],
          callouts: [
            { n: 1, x: 14, y: 66 },
            { n: 2, x: 12, y: 48 },
            { n: 3, x: 14, y: 24 },
            { n: 4, x: 9.2, y: 7 },
          ],
        },
        {
          name: "Side",
          width: 13,
          height: 72,
          prims: [
            { t: "rect", x: 1.3, y: 0, w: 2.4, h: 56 },
            { t: "rect", x: 1.3, y: 56, w: 0.4, h: 16 },
            { t: "rect", x: 3.7, y: 40, w: 5, h: 13, r: 0.4 },
            { t: "rect", x: 3.7, y: 14, w: 9.3, h: 20, r: 0.6 },
            { t: "poly", points: [[3.4, 32], [13, 32], [13, 35], [3.4, 35]], closed: true },
          ],
        },
        {
          name: "Top",
          width: 16,
          height: 13,
          noHeightDim: true,
          prims: [
            { t: "rect", x: 0.6, y: 3.4, w: 14.8, h: 9.6, r: 0.4 },
            { t: "circle", cx: 8, cy: 2.5, r: 1.2 },
            { t: "rect", x: 0, y: 1.3, w: 16, h: 0.4 },
          ],
        },
      ],
      legend: [
        { n: 1, text: "Sign panel, 16 × 16 in aluminum" },
        { n: 2, text: "Bag dispenser, 400 header-pack bags" },
        { n: 3, text: "Bin, 10 gal, hinged lid, liner ring" },
        { n: 4, text: "Post, 2-3/8\" OD, 18\" embed (not shown)" },
      ],
    },
    shots: [
      { shotId: "WS-01", brief: "Station installed at a park entrance gate, dog and owner walking past, morning light." },
      { shotId: "WS-02", brief: "Studio, three-quarter view on chalk background." },
      { shotId: "WS-03", brief: "Close-up: hand pulling a bag from the dispenser." },
    ],
    downloads: [specSheet("park-station-400"), install, cad],
    related: ["header-bags-case", "station-bin-liners", "rules-sign-18x24", "station-service"],
    consumables: ["header-bags-case", "station-bin-liners"],
    fieldNote: {
      text: "Put the station on the exit side of the gate, not the entrance. People pick up on the way out.",
      from: "FetchField install crew",
    },
  },
  {
    storefront: "pro",
    slug: "roll-dispenser",
    name: "Roll Bag Dispenser",
    category: "waste-stations",
    model: "FF-RD200",
    summary: "Wall- or post-mount dispenser for 200-bag rolls. Adds bags to an existing bin.",
    description: [
      "For sites that already have trash cans and only need bags. It mounts to a wall, a fence post, or our 2-3/8\" post with the included U-bolts.",
      "The locking front keeps bags from being stripped out in one go. One roll lasts most small properties a week.",
    ],
    highlights: ["200-bag roll", "Locking front", "Wall or post mount", "Aluminum, no rust"],
    specs: [
      { label: "Overall size", value: "6 × 4 × 8 in", note: "W × D × H" },
      { label: "Shipping weight", value: "2.5 lb" },
      { label: "Materials", value: "0.09\" aluminum" },
      { label: "Finish", value: "Powder coat, Park Green" },
      { label: "Capacity", value: "1 roll · 200 bags" },
      { label: "Mounting", value: "4 screws or 2 U-bolts", note: "hardware included" },
      { label: "Warranty", value: "5 yr" },
      { label: "Country of origin", value: "USA", note: "per manufacturer" },
      { label: "Lead time", value: "Ships in 3–5 business days" },
    ],
    leadTime: "Ships in 3–5 business days",
    pricing: {
      kind: "tiers",
      unit: "each",
      tiers: [
        { minQty: 1, maxQty: 9, priceCents: 6400 },
        { minQty: 10, maxQty: 49, priceCents: 5700 },
        { minQty: 50, maxQty: null, priceCents: 4900 },
      ],
    },
    drawing: {
      title: "Roll Bag Dispenser",
      number: "RD200-01",
      views: [
        {
          name: "Front",
          width: 6,
          height: 8,
          prims: [
            { t: "rect", x: 0, y: 0, w: 6, h: 8, r: 0.3 },
            { t: "circle", cx: 3, cy: 4.6, r: 2.1, hidden: true },
            { t: "rect", x: 1.5, y: 0.8, w: 3, h: 0.5, r: 0.25 },
            { t: "circle", cx: 5.1, cy: 7.1, r: 0.3 },
          ],
          callouts: [{ n: 1, x: 4.5, y: 1.05 }, { n: 2, x: 5.1, y: 7.1 }],
        },
        { name: "Side", width: 4, height: 8, prims: [{ t: "rect", x: 0, y: 0, w: 4, h: 8, r: 0.3 }, { t: "rect", x: 0, y: 0, w: 0.3, h: 8, fill: true }] },
      ],
      legend: [{ n: 1, text: "Bag slot, tear-off edge" }, { n: 2, text: "Keyed lock" }],
    },
    shots: [
      { shotId: "RD-01", brief: "Mounted on a wood fence post beside an apartment dog run." },
      { shotId: "RD-02", brief: "Studio, front view, lid open showing roll." },
    ],
    downloads: [specSheet("roll-dispenser"), install],
    related: ["roll-bags-case", "park-station-400"],
    consumables: ["roll-bags-case"],
  },
  {
    storefront: "pro",
    slug: "header-bags-case",
    name: "Header-Pack Bags, case of 2,000",
    category: "bags-refills",
    model: "FF-BH2000",
    summary: "Fits every header-pack dispenser, including ours. 9 × 13 in, 0.7 mil.",
    description: [
      "Standard header-pack bags: 200 bags per pack, 10 packs per case. They load from the top of any header-pack dispenser without tools.",
      "Mixed tier pricing: cases of header and roll bags count together toward your quantity tier.",
    ],
    highlights: ["2,000 bags per case", "9 × 13 in", "0.7 mil", "Ships from stock"],
    specs: [
      { label: "Bag size", value: "9 × 13 in", note: "229 × 330 mm" },
      { label: "Thickness", value: "0.7 mil" },
      { label: "Count", value: "10 packs × 200 = 2,000" },
      { label: "Material", value: "HDPE" },
      { label: "Case size", value: "15 × 10 × 9 in · 21 lb" },
      { label: "Country of origin", value: "USA", note: "per manufacturer" },
      { label: "Lead time", value: "Ships in 1–2 business days" },
    ],
    leadTime: "Ships in 1–2 business days",
    pricing: {
      kind: "tiers",
      unit: "per case",
      tiers: [
        { minQty: 1, maxQty: 4, priceCents: 8900 },
        { minQty: 5, maxQty: 19, priceCents: 7900 },
        { minQty: 20, maxQty: null, priceCents: 6900 },
      ],
    },
    shots: [{ shotId: "BR-01", brief: "Open case on a maintenance cart, packs visible, park in background." }],
    downloads: [specSheet("header-bags-case")],
    related: ["park-station-400", "station-bin-liners", "roll-bags-case"],
    fieldNote: { text: "A busy 1-acre park goes through about one case every six weeks per station. Order two and you'll never run dry between deliveries.", from: "FetchField service team" },
  },
  {
    storefront: "pro",
    slug: "roll-bags-case",
    name: "Roll Bags, case of 1,600",
    category: "bags-refills",
    model: "FF-BR1600",
    summary: "8 rolls of 200 for roll dispensers. 8 × 12 in, 0.6 mil.",
    description: ["Perforated rolls that feed one bag at a time. Fits our Roll Bag Dispenser and most roll-type dispensers with a 1\" core."],
    highlights: ["1,600 bags per case", "8 × 12 in", "1\" core", "Ships from stock"],
    specs: [
      { label: "Bag size", value: "8 × 12 in", note: "203 × 305 mm" },
      { label: "Thickness", value: "0.6 mil" },
      { label: "Count", value: "8 rolls × 200 = 1,600" },
      { label: "Core", value: "1 in" },
      { label: "Case size", value: "12 × 12 × 8 in · 14 lb" },
      { label: "Lead time", value: "Ships in 1–2 business days" },
    ],
    leadTime: "Ships in 1–2 business days",
    pricing: {
      kind: "tiers",
      unit: "per case",
      tiers: [
        { minQty: 1, maxQty: 4, priceCents: 7400 },
        { minQty: 5, maxQty: 19, priceCents: 6600 },
        { minQty: 20, maxQty: null, priceCents: 5900 },
      ],
    },
    shots: [{ shotId: "BR-02", brief: "Studio: one roll unspooled across chalk background, case behind." }],
    downloads: [specSheet("roll-bags-case")],
    related: ["roll-dispenser", "header-bags-case"],
  },
  {
    storefront: "pro",
    slug: "station-bin-liners",
    name: "Bin Liners, case of 250",
    category: "bags-refills",
    model: "FF-BL250",
    summary: "Liners sized for the Park Station 400 bin. 24 × 24 in, 1.2 mil.",
    description: ["Heavy enough to lift out full without tearing. Sized to the 10-gallon bin; also fits most 7–10 gallon cans."],
    highlights: ["250 per case", "24 × 24 in", "1.2 mil", "Fits 7–10 gal"],
    specs: [
      { label: "Liner size", value: "24 × 24 in" },
      { label: "Thickness", value: "1.2 mil LLDPE" },
      { label: "Count", value: "250" },
      { label: "Lead time", value: "Ships in 1–2 business days" },
    ],
    leadTime: "Ships in 1–2 business days",
    pricing: {
      kind: "tiers",
      unit: "per case",
      tiers: [
        { minQty: 1, maxQty: 9, priceCents: 4200 },
        { minQty: 10, maxQty: null, priceCents: 3600 },
      ],
    },
    shots: [{ shotId: "BR-03", brief: "Liner being fitted into a station bin, hands in work gloves." }],
    downloads: [specSheet("station-bin-liners")],
    related: ["park-station-400", "header-bags-case"],
  },
  {
    storefront: "pro",
    slug: "a-frame-climb",
    name: "A-Frame Climb",
    category: "agility",
    model: "FF-AG110",
    summary: "Two 7 ft ramps meeting at a 5 ft apex. Slat-textured, anchored at four points.",
    description: [
      "A lower, wider A-frame than competition equipment, built for dogs of every size meeting it for the first time. Cross slats every 12 in give paws something to grip in wet weather.",
      "Ships in two ramp sections with a steel hinge. Anchors to a concrete pad or with 30\" ground spikes.",
    ],
    highlights: ["5 ft apex", "36 in wide ramps", "Recycled HDPE deck", "Anchors at 4 points"],
    specs: [
      { label: "Overall size", value: "36 × 132 × 60 in", note: "W × L × H" },
      { label: "Shipping weight", value: "310 lb, 2 crates" },
      { label: "Deck", value: "Recycled HDPE, slat texture" },
      { label: "Frame", value: "Galvanized steel, powder coat" },
      { label: "Rated load", value: "400 lb distributed" },
      { label: "Mounting", value: "Surface mount or 30\" ground spikes" },
      { label: "Warranty", value: "10 yr deck · 5 yr frame" },
      { label: "Country of origin", value: "USA", note: "per manufacturer" },
      { label: "Lead time", value: "4–6 weeks" },
    ],
    leadTime: "Ships in 4–6 weeks",
    pricing: {
      kind: "tiers",
      unit: "each",
      tiers: [
        { minQty: 1, maxQty: 2, priceCents: 289000 },
        { minQty: 3, maxQty: 9, priceCents: 269000 },
        { minQty: 10, maxQty: null, priceCents: 249000 },
      ],
    },
    drawing: {
      title: "A-Frame Climb",
      number: "AG110-01",
      views: [
        {
          name: "Side",
          width: 132,
          height: 60,
          prims: [
            { t: "poly", points: [[0, 0], [66, 60], [132, 0]] },
            { t: "poly", points: [[4, 0], [66, 56.4], [128, 0]], hidden: true },
            { t: "line", x1: 30, y1: 0, x2: 30, y2: 27.3 },
            { t: "line", x1: 102, y1: 0, x2: 102, y2: 27.3 },
            { t: "line", x1: 30, y1: 14, x2: 102, y2: 14 },
            { t: "line", x1: 66, y1: 0, x2: 66, y2: 60, center: true },
          ],
          callouts: [{ n: 1, x: 99, y: 30 }, { n: 2, x: 66, y: 60 }, { n: 3, x: 102, y: 8 }],
        },
        {
          name: "Front",
          width: 36,
          height: 60,
          prims: [
            { t: "poly", points: [[0, 0], [0, 4], [18, 60], [36, 4], [36, 0]] },
            { t: "line", x1: 0, y1: 4, x2: 36, y2: 4 },
            { t: "rect", x: 2, y: 0, w: 3, h: 30, hidden: true },
            { t: "rect", x: 31, y: 0, w: 3, h: 30, hidden: true },
          ],
        },
      ],
      legend: [
        { n: 1, text: "Ramp deck, 36 × 84 in, slats at 12 in" },
        { n: 2, text: "Apex hinge, galvanized steel" },
        { n: 3, text: "Brace frame with anchor plates" },
      ],
    },
    shots: [
      { shotId: "AG-01", brief: "Medium dog mid-climb on the A-frame at a city dog park, owner watching." },
      { shotId: "AG-02", brief: "Studio side view on chalk background." },
    ],
    downloads: [specSheet("a-frame-climb"), install, cad],
    related: ["weave-poles-6", "tire-jump", "k9-turf"],
  },
  {
    storefront: "pro",
    slug: "weave-poles-6",
    name: "Weave Poles, set of 6",
    category: "agility",
    model: "FF-AG206",
    summary: "Six 40\" poles at 24\" spacing on a single ground-anchored base.",
    description: ["Flexible poles on a steel base rail. Poles unscrew for winter storage and replace individually."],
    highlights: ["6 poles, 24 in spacing", "40 in tall", "Flexible poles", "Single base rail"],
    specs: [
      { label: "Overall size", value: "124 × 12 × 40 in", note: "L × W × H" },
      { label: "Shipping weight", value: "64 lb" },
      { label: "Poles", value: "1 in PVC, flexible base" },
      { label: "Base", value: "Steel rail, powder coat" },
      { label: "Mounting", value: "4 ground spikes, included" },
      { label: "Warranty", value: "3 yr" },
      { label: "Lead time", value: "2–4 weeks" },
    ],
    leadTime: "Ships in 2–4 weeks",
    pricing: {
      kind: "tiers",
      unit: "per set",
      tiers: [
        { minQty: 1, maxQty: 2, priceCents: 74900 },
        { minQty: 3, maxQty: null, priceCents: 67900 },
      ],
    },
    drawing: {
      title: "Weave Poles",
      number: "AG206-01",
      views: [
        {
          name: "Side",
          width: 124,
          height: 40,
          prims: [
            { t: "rect", x: 0, y: 0, w: 124, h: 2 },
            ...[2, 26, 50, 74, 98, 122].map((x) => ({ t: "rect" as const, x: x - 0.5, y: 2, w: 1, h: 38 })),
          ],
          callouts: [{ n: 1, x: 26, y: 30 }, { n: 2, x: 110, y: 1 }],
        },
        {
          name: "Front",
          width: 12,
          height: 40,
          prims: [
            { t: "rect", x: 0, y: 0, w: 12, h: 2 },
            { t: "rect", x: 5.5, y: 2, w: 1, h: 38 },
            { t: "line", x1: 6, y1: 0, x2: 6, y2: 40, center: true },
          ],
        },
      ],
      legend: [{ n: 1, text: "Pole, 1 in PVC, 24 in on center" }, { n: 2, text: "Base rail with spike tabs" }],
    },
    shots: [{ shotId: "AG-03", brief: "Dog weaving through poles, motion blur on tail, late afternoon." }],
    downloads: [specSheet("weave-poles-6"), install],
    related: ["a-frame-climb", "tire-jump"],
  },
  {
    storefront: "pro",
    slug: "tire-jump",
    name: "Tire Jump",
    category: "agility",
    model: "FF-AG330",
    summary: "24\" ring on a steel frame, height set with a pin at 12, 18 or 24 in.",
    description: ["A soft-sided ring rather than a real tire, so no trapped water and no mosquitoes. The pin adjusts the ring height without tools."],
    highlights: ["24 in ring", "3 height settings", "No standing water", "Steel frame"],
    specs: [
      { label: "Overall size", value: "48 × 24 × 54 in", note: "W × D × H" },
      { label: "Ring opening", value: "24 in" },
      { label: "Ring heights", value: "12 / 18 / 24 in to bottom" },
      { label: "Frame", value: "2 in square steel, powder coat" },
      { label: "Mounting", value: "Surface mount or embed" },
      { label: "Warranty", value: "5 yr frame" },
      { label: "Lead time", value: "3–5 weeks" },
    ],
    leadTime: "Ships in 3–5 weeks",
    pricing: {
      kind: "tiers",
      unit: "each",
      tiers: [
        { minQty: 1, maxQty: 2, priceCents: 118000 },
        { minQty: 3, maxQty: null, priceCents: 106000 },
      ],
    },
    drawing: {
      title: "Tire Jump",
      number: "AG330-01",
      views: [
        {
          name: "Front",
          width: 48,
          height: 54,
          prims: [
            { t: "rect", x: 0, y: 0, w: 2, h: 54 },
            { t: "rect", x: 46, y: 0, w: 2, h: 54 },
            { t: "rect", x: 0, y: 52, w: 48, h: 2 },
            { t: "circle", cx: 24, cy: 30, r: 15 },
            { t: "circle", cx: 24, cy: 30, r: 12 },
            { t: "line", x1: 24, y1: 45, x2: 24, y2: 52 },
            { t: "line", x1: 9, y1: 30, x2: 2, y2: 30 },
            { t: "line", x1: 39, y1: 30, x2: 46, y2: 30 },
            { t: "line", x1: 24, y1: 0, x2: 24, y2: 54, center: true },
          ],
          callouts: [{ n: 1, x: 36, y: 22 }, { n: 2, x: 46, y: 30 }],
        },
        { name: "Side", width: 24, height: 54, prims: [{ t: "rect", x: 11, y: 0, w: 2, h: 54 }, { t: "rect", x: 0, y: 0, w: 24, h: 1.5 }, { t: "rect", x: 9.5, y: 15, w: 5, h: 30, r: 2 }] },
      ],
      legend: [{ n: 1, text: "Ring, 24 in opening, padded" }, { n: 2, text: "Height pin, 3 positions" }],
    },
    shots: [{ shotId: "AG-04", brief: "Small terrier jumping through the ring, owner crouched with treat." }],
    downloads: [specSheet("tire-jump"), install],
    related: ["a-frame-climb", "weave-poles-6"],
  },
  {
    storefront: "pro",
    slug: "pedestal-fountain",
    name: "Pedestal Fountain with Pet Bowl",
    category: "water",
    model: "FF-WF420",
    summary: "People fountain at 36 in, dog bowl at 8 in, one 3/4\" supply line.",
    description: [
      "A push-button bubbler for people and a separate foot-pedal bowl fill for dogs. The bowl drains between uses, so it doesn't sit stagnant.",
      "Freeze-resistant valve option drains the riser below frost line when the button is released.",
    ],
    highlights: ["Push-button bubbler", "Foot-pedal bowl fill", "3/4 in supply", "Freeze-resistant option"],
    specs: [
      { label: "Overall size", value: "30 × 12 × 42 in", note: "W × D × H" },
      { label: "Shipping weight", value: "118 lb" },
      { label: "Body", value: "Powder-coated steel pedestal" },
      { label: "Bowl", value: "Stainless steel, self-draining" },
      { label: "Supply", value: "3/4 in NPT, 30–80 psi" },
      { label: "Drain", value: "1-1/2 in to dry well or sanitary" },
      { label: "Mounting", value: "Surface mount to concrete pad" },
      { label: "Warranty", value: "5 yr" },
      { label: "Lead time", value: "4–5 weeks" },
    ],
    leadTime: "Ships in 4–5 weeks",
    pricing: {
      kind: "tiers",
      unit: "each",
      tiers: [
        { minQty: 1, maxQty: 2, priceCents: 324000 },
        { minQty: 3, maxQty: null, priceCents: 298000 },
      ],
    },
    drawing: {
      title: "Pedestal Fountain",
      number: "WF420-01",
      views: [
        {
          name: "Front",
          width: 30,
          height: 42,
          prims: [
            { t: "rect", x: 0, y: 0, w: 14, h: 1.5 },
            { t: "rect", x: 2, y: 1.5, w: 10, h: 34.5 },
            { t: "poly", points: [[0, 36], [14, 36], [13, 42], [1, 42]], closed: true },
            { t: "rect", x: 16, y: 0, w: 14, h: 1.5 },
            { t: "poly", points: [[17, 8], [29, 8], [27.5, 3], [18.5, 3]], closed: true },
            { t: "rect", x: 20, y: 1.5, w: 6, h: 1.5 },
            { t: "line", x1: 12, y1: 5, x2: 17, y2: 5, hidden: true },
            { t: "rect", x: 5.5, y: 38, w: 3, h: 2, r: 0.5 },
          ],
          callouts: [{ n: 1, x: 7, y: 40 }, { n: 2, x: 23, y: 6 }, { n: 3, x: 12, y: 5 }],
        },
        { name: "Side", width: 12, height: 42, prims: [{ t: "rect", x: 1, y: 1.5, w: 10, h: 34.5 }, { t: "rect", x: 0, y: 0, w: 12, h: 1.5 }, { t: "poly", points: [[0, 36], [12, 36], [11, 42], [1, 42]], closed: true }] },
      ],
      legend: [{ n: 1, text: "Push-button bubbler" }, { n: 2, text: "Self-draining pet bowl, foot pedal fill" }, { n: 3, text: "Supply line to bowl valve" }],
    },
    shots: [{ shotId: "WF-01", brief: "Dog drinking from bowl while owner drinks from bubbler, summer." }],
    downloads: [specSheet("pedestal-fountain"), install, cad],
    related: ["park-bench-6", "park-station-400"],
  },
  {
    storefront: "pro",
    slug: "park-bench-6",
    name: "Park Bench, 6 ft",
    category: "seating-shade",
    model: "FF-SS600",
    summary: "Recycled-plastic slats on a steel frame. Seats three, no maintenance.",
    description: ["Slats won't splinter, rot or need paint. Frame feet bolt to concrete or embed in a footing."],
    highlights: ["Seats 3", "Recycled plastic slats", "Steel frame", "No painting, ever"],
    specs: [
      { label: "Overall size", value: "72 × 24 × 32 in", note: "W × D × H" },
      { label: "Seat height", value: "18 in" },
      { label: "Shipping weight", value: "142 lb" },
      { label: "Slats", value: "Recycled HDPE, Cedar or Gray" },
      { label: "Frame", value: "Steel, powder coat, Park Green" },
      { label: "Mounting", value: "Surface mount or embed" },
      { label: "Warranty", value: "20 yr slats · 5 yr frame" },
      { label: "Lead time", value: "3–4 weeks" },
    ],
    leadTime: "Ships in 3–4 weeks",
    pricing: {
      kind: "tiers",
      unit: "each",
      tiers: [
        { minQty: 1, maxQty: 4, priceCents: 94000 },
        { minQty: 5, maxQty: null, priceCents: 86000 },
      ],
    },
    drawing: {
      title: "Park Bench 6 ft",
      number: "SS600-01",
      views: [
        {
          name: "Front",
          width: 72,
          height: 32,
          prims: [
            { t: "rect", x: 4, y: 0, w: 3, h: 18 },
            { t: "rect", x: 65, y: 0, w: 3, h: 18 },
            { t: "rect", x: 0, y: 16, w: 72, h: 2.5 },
            { t: "rect", x: 0, y: 22, w: 72, h: 3.5 },
            { t: "rect", x: 0, y: 27.5, w: 72, h: 3.5 },
          ],
          callouts: [{ n: 1, x: 60, y: 29 }, { n: 2, x: 67, y: 8 }],
        },
        {
          name: "Side",
          width: 24,
          height: 32,
          prims: [
            { t: "poly", points: [[2, 0], [6, 16], [22, 16], [22, 0]] },
            { t: "rect", x: 3, y: 16, w: 19, h: 2.5 },
            { t: "poly", points: [[6, 16], [2, 32], [5, 32], [9, 18]] },
          ],
        },
      ],
      legend: [{ n: 1, text: "Backrest slats, recycled HDPE" }, { n: 2, text: "Frame leg with anchor plate" }],
    },
    shots: [{ shotId: "SS-01", brief: "Two people on the bench, dogs at their feet, shade tree overhead." }],
    downloads: [specSheet("park-bench-6"), install],
    related: ["pedestal-fountain", "rules-sign-18x24"],
  },
  {
    storefront: "pro",
    slug: "double-gate-entry",
    name: "Double-Gate Entry Vestibule",
    category: "fencing-gates",
    model: "FF-FG-DGE",
    summary: "An airlock entry: two self-closing gates around a holding pen, so dogs can't bolt.",
    description: [
      "The standard entry for off-leash areas. Owners unclip leashes inside the vestibule with both gates shut.",
      "Priced per site: gate count, fence height, grade and whether you need a separate maintenance gate all change the materials.",
    ],
    highlights: ["Two self-closing gates", "Gravity latches", "5 ft or 6 ft", "Maintenance gate option"],
    specs: [
      { label: "Typical vestibule", value: "8 × 10 ft" },
      { label: "Fence height", value: "5 ft or 6 ft" },
      { label: "Gates", value: "4 ft wide, self-closing hinges" },
      { label: "Latch", value: "Gravity, 2-sided, ADA-operable" },
      { label: "Materials", value: "Galvanized steel, vinyl-coated mesh" },
      { label: "Lead time", value: "3–6 weeks after drawings" },
    ],
    leadTime: "3–6 weeks after drawing approval",
    pricing: {
      kind: "custom",
      reason: "Price depends on gate count, fence height and site grade. Send a site plan or dimensions with your quote request and we'll price the full bill of materials, usually within two business days.",
      fromCents: 480000,
    },
    shots: [{ shotId: "FG-01", brief: "Owner closing the outer gate while dog waits inside the vestibule." }],
    downloads: [specSheet("double-gate-entry"), cad],
    related: ["rules-sign-18x24", "park-station-400"],
  },
  {
    storefront: "pro",
    slug: "k9-turf",
    name: "K9 Synthetic Turf",
    category: "surfacing",
    model: "FF-SU-K9T",
    summary: "Permeable-backed turf that drains 30+ in/hr. Priced per square foot, 500 sq ft minimum.",
    description: ["Short-pile turf with a fully permeable backing, laid over compacted aggregate. Rinses clean with a hose; antimicrobial infill is optional."],
    highlights: ["Drains 30+ in/hr", "1.25 in pile", "Permeable backing", "500 sq ft minimum"],
    specs: [
      { label: "Pile height", value: "1.25 in" },
      { label: "Face weight", value: "70 oz/sq yd" },
      { label: "Drainage", value: "30+ in/hr", note: "per manufacturer test" },
      { label: "Roll width", value: "15 ft" },
      { label: "Base", value: "4 in compacted aggregate, not included" },
      { label: "Warranty", value: "8 yr UV" },
      { label: "Lead time", value: "2–3 weeks" },
    ],
    leadTime: "Ships in 2–3 weeks",
    pricing: {
      kind: "tiers",
      unit: "per sq ft",
      tiers: [
        { minQty: 500, maxQty: 1999, priceCents: 495 },
        { minQty: 2000, maxQty: 9999, priceCents: 445 },
        { minQty: 10000, maxQty: null, priceCents: 395 },
      ],
    },
    shots: [{ shotId: "SU-01", brief: "Close-up of turf after rain, water beading, paw prints." }],
    downloads: [specSheet("k9-turf"), install],
    related: ["a-frame-climb", "park-bench-6"],
  },
  {
    storefront: "pro",
    slug: "rules-sign-18x24",
    name: "Park Rules Sign, 18 × 24 in",
    category: "signage",
    model: "FF-SG1824",
    summary: "Aluminum rules sign with your park name. Standard or custom text, same price.",
    description: ["0.080 aluminum with a UV-laminated print. Mounts to our 2-3/8\" post or any flat surface. We send a proof before printing."],
    highlights: ["0.080 aluminum", "UV laminate", "Proof before print", "Custom text included"],
    specs: [
      { label: "Size", value: "18 × 24 in" },
      { label: "Material", value: "0.080 aluminum" },
      { label: "Finish", value: "UV-laminated digital print" },
      { label: "Mounting", value: "Post brackets or 4 holes" },
      { label: "Warranty", value: "7 yr fade" },
      { label: "Lead time", value: "7–10 business days after proof" },
    ],
    leadTime: "7–10 business days after proof approval",
    pricing: {
      kind: "tiers",
      unit: "each",
      tiers: [
        { minQty: 1, maxQty: 4, priceCents: 14900 },
        { minQty: 5, maxQty: null, priceCents: 12900 },
      ],
    },
    drawing: {
      title: "Rules Sign 18x24",
      number: "SG1824-01",
      views: [
        {
          name: "Front",
          width: 18,
          height: 72,
          prims: [
            { t: "rect", x: 7.8, y: 0, w: 2.4, h: 70 },
            { t: "rect", x: 0, y: 46, w: 18, h: 24, r: 0.4 },
            { t: "rect", x: 1.5, y: 64, w: 15, h: 3, fill: true },
            ...[60, 57, 54, 51].map((y) => ({ t: "line" as const, x1: 2, y1: y, x2: 14, y2: y })),
          ],
          callouts: [{ n: 1, x: 16.5, y: 65.5 }, { n: 2, x: 10.2, y: 20 }],
        },
      ],
      legend: [{ n: 1, text: "Park name band" }, { n: 2, text: "Post, 2-3/8 in OD (optional)" }],
    },
    shots: [{ shotId: "SG-01", brief: "Sign at a park entrance, readable, dogs out of focus behind." }],
    downloads: [specSheet("rules-sign-18x24")],
    related: ["park-station-400", "double-gate-entry"],
  },
  {
    storefront: "pro",
    slug: "station-service",
    name: "Station Service Plan",
    category: "service-plans",
    model: "FF-SP-MNT",
    summary: "We empty bins, restock bags and report damage. Priced per station, per month.",
    description: [
      "Weekly service visits: empty and reline bins, refill dispensers, wipe down, and a photo report after every visit. Bags and liners are included.",
      "Available where we have a crew. Check your ZIP below. Month to month, 30 days' notice to cancel.",
    ],
    highlights: ["Weekly visits", "Bags & liners included", "Photo report each visit", "Month to month"],
    specs: [
      { label: "Visit frequency", value: "Weekly", note: "2× weekly available" },
      { label: "Included", value: "Bags, liners, disposal" },
      { label: "Reporting", value: "Photo + fill level per visit" },
      { label: "Term", value: "Month to month, 30 days' notice" },
      { label: "Install", value: "Optional, per station" },
    ],
    leadTime: "Starts within 2 weeks",
    pricing: {
      kind: "tiers",
      unit: "per station / month",
      tiers: [
        { minQty: 1, maxQty: 4, priceCents: 6500 },
        { minQty: 5, maxQty: 19, priceCents: 5500 },
        { minQty: 20, maxQty: null, priceCents: 4500 },
      ],
    },
    service: { perStationMonthlyCents: 6500, installCents: 18500 },
    shots: [{ shotId: "SP-01", brief: "Crew member restocking a station from a truck tailgate, early morning." }],
    downloads: [specSheet("station-service")],
    related: ["park-station-400", "header-bags-case"],
  },
];
