import type { ShopProduct, ShopVariant } from "./types";

/*
 * SAMPLE CATALOG. In production these rows come from the curated catalog
 * (import → vet → rewrite → publish). Availability and transit windows come
 * from the supplier sync. Nothing here names or links to a supplier.
 */

const variants = (base: string, colors: string[] | null, sizes: string[] | null, soldOut: string[] = []): ShopVariant[] => {
  const cs = colors ?? [undefined];
  const ss = sizes ?? [undefined];
  return cs.flatMap((c) =>
    ss.map((s) => {
      const sku = [base, c?.slice(0, 3).toUpperCase(), s].filter(Boolean).join("-");
      return { sku, color: c, size: s, availability: soldOut.includes(sku) ? "sold_out" : "available" } as ShopVariant;
    }),
  );
};

const moss = { name: "Moss", hex: "#4F6B3A" };
const clayC = { name: "Rust", hex: "#A5522E" };
const slate = { name: "Slate", hex: "#3E4A52" };
const sand = { name: "Sand", hex: "#CDBB93" };

export const shopProducts: ShopProduct[] = [
  {
    storefront: "shop",
    slug: "trail-leash-6ft",
    name: "Trail Leash, 6 ft",
    category: "walk",
    summary: "3/4 in climbing-rope leash with a locking carabiner. Reflective tracer.",
    description: [
      "Round climbing-rope leash that doesn't get stiff when it dries out. The locking carabiner can't pop open on a collar ring.",
      "A second clip point 18 in from the handle shortens it for traffic without looping it around your wrist.",
    ],
    priceCents: 3400,
    colors: [moss, clayC, slate],
    variants: variants("FF-WLK-TL6", ["Moss", "Rust", "Slate"], null, ["FF-WLK-TL6-RUS"]),
    materials: ["3/4 in (19 mm) polyester climbing rope", "Aluminum locking carabiner", "Reflective tracer thread"],
    care: ["Hand wash, air dry", "Rinse after saltwater"],
    dogSizes: ["S", "M", "L", "XL"],
    transit: { minDays: 6, maxDays: 10 },
    weight: "7.4 oz (210 g)",
    shots: [
      { shotId: "TL-01", brief: "Leash clipped to a muddy dog on a trail, owner's hand in frame, overcast." },
      { shotId: "TL-02", brief: "Studio: leash coiled on chalk background, carabiner detail." },
    ],
    fieldNote: { text: "We tested the carabiner on a 70 lb dog lunging at geese. It held. The handle padding is thin, so wear gloves in winter.", from: "Product testing, FetchField" },
    pairsWith: ["everyday-collar", "bag-clip-dispenser"],
  },
  {
    storefront: "shop",
    slug: "everyday-collar",
    name: "Everyday Collar",
    category: "walk",
    summary: "Waxed-canvas collar with a steel buckle and a separate ID ring.",
    description: ["Waxed canvas over nylon webbing: stiff at first, broken in after two weeks. The ID ring is separate from the leash D-ring so tags don't jangle under load."],
    priceCents: 2400,
    colors: [moss, clayC, sand],
    sizes: [
      { label: "S", fit: "Neck 10–13 in" },
      { label: "M", fit: "Neck 13–17 in" },
      { label: "L", fit: "Neck 16–21 in" },
    ],
    variants: variants("FF-WLK-EC", ["Moss", "Rust", "Sand"], ["S", "M", "L"], ["FF-WLK-EC-SAN-L"]),
    sizeGuide: {
      note: "Measure around the neck where the collar sits, then add two fingers.",
      columns: ["Size", "Neck (in)", "Neck (cm)", "Width"],
      rows: [
        ["S", "10–13", "25–33", "3/4 in · 19 mm"],
        ["M", "13–17", "33–43", "1 in · 25 mm"],
        ["L", "16–21", "41–53", "1 in · 25 mm"],
      ],
    },
    materials: ["Waxed cotton canvas over nylon webbing", "Stainless steel buckle and D-ring"],
    care: ["Wipe clean", "Re-wax yearly with any fabric wax"],
    dogSizes: ["S", "M", "L"],
    transit: { minDays: 7, maxDays: 12 },
    shots: [{ shotId: "EC-01", brief: "Collar on a short-haired dog, close crop, natural light." }],
    pairsWith: ["trail-leash-6ft"],
  },
  {
    storefront: "shop",
    slug: "field-harness",
    name: "Field Harness",
    category: "walk",
    summary: "Y-front harness with front and back clips. Four adjustment points.",
    description: ["The Y-front keeps straps off the shoulder joint. Front clip for pullers, back clip for everyone else. A grab handle on the back for stiles and car doors."],
    priceCents: 4800,
    colors: [moss, slate],
    sizes: [
      { label: "S", fit: "Chest 17–22 in" },
      { label: "M", fit: "Chest 22–28 in" },
      { label: "L", fit: "Chest 27–34 in" },
      { label: "XL", fit: "Chest 32–40 in" },
    ],
    variants: variants("FF-WLK-FH", ["Moss", "Slate"], ["S", "M", "L", "XL"]),
    sizeGuide: {
      note: "Measure the widest part of the chest, just behind the front legs.",
      columns: ["Size", "Chest (in)", "Chest (cm)", "Neck (in)", "Typical weight"],
      rows: [
        ["S", "17–22", "43–56", "12–16", "10–25 lb"],
        ["M", "22–28", "56–71", "16–21", "25–50 lb"],
        ["L", "27–34", "69–86", "20–26", "50–80 lb"],
        ["XL", "32–40", "81–102", "24–30", "80–120 lb"],
      ],
    },
    materials: ["Nylon webbing, padded mesh lining", "Aluminum V-ring front clip", "Steel back D-ring"],
    care: ["Machine wash cold in a bag", "Air dry"],
    dogSizes: ["S", "M", "L", "XL"],
    transit: { minDays: 7, maxDays: 12 },
    shots: [{ shotId: "FH-01", brief: "Dog in harness sitting at a trailhead sign, owner's boots visible." }],
    pairsWith: ["trail-leash-6ft"],
  },
  {
    storefront: "shop",
    slug: "long-line-30ft",
    name: "Long Line, 30 ft",
    category: "play",
    summary: "Biothane recall line. Doesn't soak up water, wipes clean.",
    description: ["For recall practice in open fields. Biothane stays light when wet and doesn't pick up burrs. Drag it, don't hold it wrapped around a hand."],
    priceCents: 3900,
    colors: [clayC, moss],
    variants: variants("FF-PLY-LL30", ["Rust", "Moss"], null),
    materials: ["1/2 in (13 mm) coated webbing", "Brass snap"],
    care: ["Wipe or rinse", "Dishwasher safe (top rack)"],
    dogSizes: ["S", "M", "L", "XL"],
    transit: { minDays: 6, maxDays: 10 },
    shots: [{ shotId: "LL-01", brief: "Line trailing across wet grass behind a running dog, wide shot." }],
  },
  {
    storefront: "shop",
    slug: "field-ball-2pk",
    name: "Field Ball, 2-pack",
    category: "play",
    summary: "2.5 in rubber ball that floats and bounces unpredictably on grass.",
    description: [
      "Natural rubber, hollow, with a seam pattern that sends it sideways on a bounce. Floats.",
      "Our testers' dogs had these for three months of daily fetch. One was lost in a pond, and none were chewed through. Heavy chewers should play supervised.",
    ],
    priceCents: 1600,
    colors: [clayC, sand],
    variants: variants("FF-PLY-FB2", ["Rust", "Sand"], null),
    materials: ["Natural rubber"],
    care: ["Rinse, air dry", "Replace when cracked"],
    dogSizes: ["S", "M", "L"],
    transit: { minDays: 6, maxDays: 10 },
    shots: [{ shotId: "FB-01", brief: "Ball mid-air above a field, dog blurred in background." }],
  },
  {
    storefront: "shop",
    slug: "tug-rope",
    name: "Tug Rope, 18 in",
    category: "play",
    summary: "Braided cotton-poly tug with two knots and a fleece grip.",
    description: ["Tight braid so it doesn't unravel after the first week. Fleece grip end for you."],
    priceCents: 1400,
    variants: variants("FF-PLY-TR18", null, null),
    materials: ["Cotton-poly rope", "Fleece handle"],
    care: ["Machine wash cold", "Air dry"],
    dogSizes: ["M", "L", "XL"],
    transit: { minDays: 7, maxDays: 12 },
    shots: [{ shotId: "TR-01", brief: "Two dogs tugging, low angle on grass." }],
  },
  {
    storefront: "shop",
    slug: "collapsible-bowl",
    name: "Collapsible Trail Bowl",
    category: "eat-drink",
    summary: "Holds 3 cups (710 ml). Folds to 1/2 in and clips to a leash.",
    description: ["Silicone bowl on a stiff rim, so it doesn't fold while your dog drinks. The carabiner clips to a pack strap or leash handle."],
    priceCents: 1200,
    colors: [moss, clayC, slate],
    variants: variants("FF-EAT-CB3", ["Moss", "Rust", "Slate"], null),
    materials: ["Food-grade silicone", "Polypropylene rim", "Aluminum clip"],
    care: ["Dishwasher safe"],
    dogSizes: ["XS", "S", "M", "L", "XL"],
    transit: { minDays: 6, maxDays: 10 },
    shots: [{ shotId: "CB-01", brief: "Dog drinking from bowl on a rock at a trail break." }],
    pairsWith: ["travel-bottle"],
  },
  {
    storefront: "shop",
    slug: "steel-bowl-set",
    name: "Steel Bowl Set",
    category: "eat-drink",
    summary: "Two stainless bowls in a non-slip base. 4 cups (950 ml) each.",
    description: ["Heavy-gauge stainless that doesn't dent when kicked. The base lifts off to wash."],
    priceCents: 3200,
    colors: [moss, sand],
    variants: variants("FF-EAT-SB4", ["Moss", "Sand"], null),
    materials: ["18/8 stainless steel bowls", "Bamboo-fiber base with rubber feet"],
    care: ["Bowls dishwasher safe", "Wipe base"],
    dogSizes: ["M", "L", "XL"],
    transit: { minDays: 8, maxDays: 13 },
    shots: [{ shotId: "SB-01", brief: "Bowl set on a kitchen floor, dog's nose entering frame." }],
  },
  {
    storefront: "shop",
    slug: "travel-bottle",
    name: "Travel Water Bottle",
    category: "travel",
    summary: "20 oz (590 ml) bottle with a flip-down trough. One-hand pour and lock.",
    description: ["Press to fill the trough, release to drain what's left back into the bottle. The lock stops it leaking in a bag."],
    priceCents: 1800,
    colors: [slate, sand],
    variants: variants("FF-TRV-WB20", ["Slate", "Sand"], null),
    materials: ["BPA-free Tritan bottle", "Silicone seals"],
    care: ["Top-rack dishwasher safe"],
    dogSizes: ["XS", "S", "M", "L", "XL"],
    transit: { minDays: 6, maxDays: 10 },
    shots: [{ shotId: "WB-01", brief: "Owner pouring for dog on a park bench, afternoon." }],
  },
  {
    storefront: "shop",
    slug: "car-seat-cover",
    name: "Back Seat Cover",
    category: "travel",
    summary: "Quilted, waterproof hammock cover with seat-belt openings.",
    description: ["Hammock mode keeps dogs out of the footwell; bench mode lets people sit too. Zippered side flaps cover the doors."],
    priceCents: 6200,
    compareAtCents: 6800,
    colors: [slate],
    sizes: [
      { label: "Standard", fit: "Seats up to 54 in wide" },
      { label: "XL", fit: "Seats up to 60 in wide (trucks, large SUVs)" },
    ],
    variants: variants("FF-TRV-SC", ["Slate"], ["Standard", "XL"]),
    sizeGuide: {
      columns: ["Size", "Width", "Depth", "Fits"],
      rows: [
        ["Standard", "54 in · 137 cm", "58 in · 147 cm", "Sedans, small–mid SUVs"],
        ["XL", "60 in · 152 cm", "64 in · 163 cm", "Crew-cab trucks, large SUVs"],
      ],
    },
    materials: ["600D polyester, TPU waterproof layer", "Rubber non-slip backing"],
    care: ["Machine wash cold, gentle", "Hang dry"],
    dogSizes: ["S", "M", "L", "XL"],
    transit: { minDays: 8, maxDays: 14 },
    shots: [{ shotId: "SC-01", brief: "Muddy dog in the back seat on the cover, door open, after a park." }],
  },
  {
    storefront: "shop",
    slug: "bag-clip-dispenser",
    name: "Bag Clip Dispenser + 8 rolls",
    category: "clean-up",
    summary: "Leash-clip dispenser and 120 bags, the same thickness we stock in park stations.",
    description: ["An aluminum canister with a clip, not a plastic bone that cracks. Comes with 8 rolls of 15 bags."],
    priceCents: 1400,
    colors: [moss, slate],
    variants: variants("FF-CLN-BC8", ["Moss", "Slate"], null),
    materials: ["Aluminum canister", "HDPE bags, 9 × 13 in, 0.7 mil"],
    care: ["Wipe clean"],
    dogSizes: ["XS", "S", "M", "L", "XL"],
    transit: { minDays: 6, maxDays: 10 },
    shots: [{ shotId: "BC-01", brief: "Dispenser clipped to a leash handle, bag half pulled." }],
  },
  {
    storefront: "shop",
    slug: "washable-mat",
    name: "Washable Crate Mat",
    category: "comfort",
    summary: "Quilted mat that fits standard crates. Machine wash, low dry.",
    description: ["Flat enough to stay put in a crate, thick enough for hard floors. Non-slip dots on the back."],
    priceCents: 3600,
    colors: [sand, slate],
    sizes: [
      { label: "M", fit: "30 × 21 in" },
      { label: "L", fit: "36 × 23 in" },
      { label: "XL", fit: "42 × 28 in" },
    ],
    variants: variants("FF-CMF-WM", ["Sand", "Slate"], ["M", "L", "XL"], ["FF-CMF-WM-SLA-XL"]),
    sizeGuide: {
      columns: ["Size", "Inches", "Centimetres", "Fits crate"],
      rows: [
        ["M", "30 × 21", "76 × 53", "30 in"],
        ["L", "36 × 23", "91 × 58", "36 in"],
        ["XL", "42 × 28", "107 × 71", "42 in"],
      ],
    },
    materials: ["Polyester quilted top, poly fill", "Non-slip silicone dots"],
    care: ["Machine wash cold", "Tumble dry low"],
    dogSizes: ["M", "L", "XL"],
    transit: { minDays: 8, maxDays: 13 },
    shots: [{ shotId: "WM-01", brief: "Tired dog asleep on the mat, evening window light." }],
  },
  {
    storefront: "shop",
    slug: "park-day-kit",
    name: "Park Day Kit",
    category: "walk",
    summary: "Trail Leash, Collapsible Trail Bowl and Bag Clip Dispenser together.",
    description: ["The three things we'd put in a first-time owner's hands on the way to the park. Colors match."],
    priceCents: 5200,
    compareAtCents: 6000,
    colors: [moss, slate],
    variants: variants("FF-KIT-PD", ["Moss", "Slate"], null),
    materials: ["See each item"],
    care: ["See each item"],
    dogSizes: ["S", "M", "L", "XL"],
    transit: { minDays: 6, maxDays: 10 },
    shots: [{ shotId: "KIT-01", brief: "Flat lay on a wooden bench: leash coiled, bowl, dispenser, wet grass edge." }],
    isBundle: { items: ["trail-leash-6ft", "collapsible-bowl", "bag-clip-dispenser"], savesCents: 800 },
  },
];
